### ISSUE TITLE
Option to drain all workload data pipeline throwing exception

### ISSUE THREAD

**Issue by HirenRNaik** [microsoft/SCMScaleUnitDevTools#109]
Hi,

I am using the latest SCMScaleUnitDevTools for LCS hosted environments. I have successfully configured Hub and Scale unit and able to execute MES and WES workloads. I need to service Hub and scale unit to 10.0.22 and hence i am using Drain all workload pipeline function but it is throwing exception as shown below.

Any help would be appreciated.

![image](https://user-images.githubusercontent.com/92958414/138370056-72fb24fe-c754-4a53-80df-2afe4e82c35f.png)
![image](https://user-images.githubusercontent.com/92958414/138370101-527611dd-fad6-43b0-857a-52cc305e7251.png)

**Comment by AndreasHassing** [comment]
Giving the tool Admin rights resolved the issue (according to internal email). This is not ideal, of course, and I believe it is fixed in App 10.0.23 or 10.0.24.
