### ISSUE TITLE
Truncate NUMBERSEQUENCEREFERENCE table during initialization

### ISSUE THREAD

**Issue by Antonstockmarr** [microsoft/SCMScaleUnitDevTools#113]
Right now we are truncating NumberSequenceScope, but not NumberSequenceReference. The two tables are linked, and they should be cleared at the same time.

**Comment by AndreasHassing** [comment]
Can we move this to the workload installation step for spokes?

Could be something like:
1. Check if there are any applied (`status = 3`) upload sessions in `RetailCDXUploadSession` table for the SYS workload.
2. If there are none: assume this is a fresh spoke and truncate bad tables (NumberSequence*, FeatureManagement*, and others, see the internal onboarding document for the full list).
3. If there are any: skip the cleanup as we assume SYS already went through once.

**Comment by Antonstockmarr** [comment]
Yes, we can do that. So that would entries with ``jobid = 'SYSHTS'``, right?

**Comment by AndreasHassing** [comment]
That's right 😊.

**Comment by AndreasHassing** [comment]
Also, this mitigation should only be applied right before installing the SYS workload, not before installing WES or MES - we will only try to install those after SYS has applied it's initial sync package.
