### ISSUE TITLE
Turn-off HUB and scale env is not accessible

### ISSUE THREAD

**Issue by IkhanKOR** [microsoft/SCMScaleUnitDevTools#118]
Scenario: Two one box VM's, one for HUB and Scale each. When turning off HUB, scale env is not accessible. 

Issue: The host file in scale is pointing to HUB IP address. Do we need to manually change the host entry or other parameters.

**Comment by AndreasHassing** [comment]
Hi @IkhanKOR,

I'm not sure I follow. Can you elaborate more?

The hub VM is shut down, and now you cannot access the scale unit AX environment, or?

Can you access the scale unit from a browser outside the environment (assuming you're using LCS cloud-hosted developer box)?

**Comment by IkhanKOR** [comment]
Hello @AndreasHassing,

Yes I cannot access the scale unit AX environment, we are using local hosted one-box vm's for both Scale and Hub.

**Comment by IkhanKOR** [comment]
> Hello @AndreasHassing,
> 
> Yes I cannot access the scale unit AX environment, we are using local hosted one-box vm's for both Scale and Hub.

**Comment by AndreasHassing** [comment]
What does your `hosts` file look like? Did you enable `UseSingleOneBox` in the `UserConfig.xml` accidentally?

**Comment by IkhanKOR** [comment]
<UseSingleOneBox>false</UseSingleOneBox> is set to false. 
Hub: 127.0.0.1	usnconeboxax1aos.cloud.onebox.dynamics.com
Scale: 192.168.121.45	usnconeboxax1aos.cloud.onebox.dynamics.com

Hub local ip is 192.168.121.45

**Comment by AndreasHassing** [comment]
@IkhanKOR: Hub and Scale unit use the same domain name? That seems off.

The Scale unit should use something like: `usnconeboxax2aos.cloud.onebox.dynamics.com`.

In the `UserConfig.xml`, put it in the `Domain` of the Scale Unit (@A):
![image](https://user-images.githubusercontent.com/639843/142170893-41dacfc0-3a84-4d17-8ce7-8e45118d6d16.png)

**Comment by AndreasHassing** [comment]
When using a different domain for the scale unit, you will not have domain collisions on IPs and should be able to access the scale unit environment regardless.

Feel free to open this issue again if these pointers did not fix your issue.
