### ISSUE TITLE
Update SysAADClientTable user ID to ScaleUnit(Management|Pipeline)

### ISSUE THREAD

**Issue by AndreasHassing** [microsoft/SCMScaleUnitDevTools#151]
During [AAD App allowlisting](https://github.com/microsoft/SCMScaleUnitDevTools/blob/87c739c8e4143315f3fd875378913b32dfe34269/src/ScaleUnitManagement/DatabaseManager/AADAppAllowListing.cs#L16-L17), we don't update the user to `ScaleUnitPipeline` for `ScaleUnits` app.

Internally reported bug from @vlgrozma.

**Comment by Antonstockmarr** [comment]
We should check if the ScaleUnitPipeline user exists in the user table. If it does we use it, otherwise we use admin.
