### ISSUE TITLE
Feature Request: In the UserConfig allow the storage emulator to be used.

### ISSUE THREAD

**Issue by alkalomo** [microsoft/SCMScaleUnitDevTools#24]
In the userConfig.xml allow for maximum one scale unit to have the AzureStorageConnectionString field blank, in which case the local storage emulator should be used for that scale unit.

**Comment by AndreasHassing** [comment]
We already have validation in place for this. Closing in favor of #3, where this needs to be considered as well (i.e. all scale units should be able to use storage emulator if they desire, but the Hub cannot).
