### ISSUE TITLE
Quality of Life improvements (round 1)

### ISSUE THREAD

**Issue by AndreasHassing** [microsoft/SCMScaleUnitDevTools#26]
This issue lists a number of quality of life improvements that can and should be added to the tool to increase developer productivity:

- [x] The tool should have a "Reset" or "Clean" action which cleans out the environment, in preparation for starting over.
    - Can start by adding as a Tool the ability to clean out the storage account. We have access to the storage connection string from web.config, so can just clean out using that.
    - Storage account wise, this is covered by #69.
- [ ] It should be possible to run individual steps or a subset of steps during scale unit configuration (for example: to avoid having to run DbSync while only wanting to invoke the configure endpoint in the AOS). Could use Sharprompt for this.
- [x] We should reset the tool after each action instead of quitting completely.
- [x] We should provide documentation on how to set up the Azure storage account(s) as there are multiple options in the process and we have no indication on what combinations we support.
   - https://github.com/microsoft/SCMScaleUnitDevTools/wiki/How-to-create-a-compatible-storage-account

**Comment by Antonstockmarr** [comment]
Resetting the tool is covered by #72

**Comment by AndreasHassing** [comment]
Creating issue for the remaining item and closing this.
