### ISSUE TITLE
Tool attempts to uninstall/stop scale unit Batch service if it does not exist

### ISSUE THREAD

**Issue by AndreasHassing** [microsoft/SCMScaleUnitDevTools#27]
This is minor; the tool currently shows an error while enabling the hybrid topology on a shared-box scale unit (when it creates the additional Batch service) - the error is benign as we ignore it, but we can avoid it completely if we just check if the Batch service is installed or not.

**Comment by gammelgaard52** [comment]
Hi,
It seems like challenge is still there.
![image](https://user-images.githubusercontent.com/16650923/107034199-ae3eeb80-67b6-11eb-849e-ef5a60a54e79.png)

Scenario:
No service installed
Repro:
Run cli.exe, select 1, select 1, select 1 (stop service)

**Comment by AndreasHassing** [comment]
Thanks @gammelgaard52, I missed that one 😊.
