### ISSUE TITLE
Ensure that there are no manual number sequences before trying to install the workloads.

### ISSUE THREAD

**Issue by alkalomo** [microsoft/SCMScaleUnitDevTools#34]

**Comment by AndreasHassing** [comment]
@alkalomo I assume this is only for scale units? What problem does it solve? If there are any manual number sequences on a scale unit before workload installation, what happens (error messages etc.)?

**Comment by AndreasHassing** [comment]
Manual number sequences can cause some problems between Scale Units and the Hub if they are manual. We need to discuss further with Gaurav and Andy on what to do here.

**Comment by AndreasHassing** [comment]
Closing as `wontfix` for now. This is not very critical and I believe changes are being made in the platform to handle the scenario better.
