### ISSUE TITLE
Provide capability to perform DB sync against project/model for the scale unit DB

### ISSUE THREAD

**Issue by alkalomo** [microsoft/SCMScaleUnitDevTools#35]
This applies to OneBox only environments, where DBsync will go against the main (hub) environment's db.

**Comment by AndreasHassing** [comment]
This is for targeting the Scale Unit DB with DbSync when `UseSingleOneBox == true` (i.e. both Hub and Scale Unit is found on the same machine), where VS makes it easy to sync single models and perform full sync against the default DB, there is nothing such for the Scale Unit DB.

This functionality should be added to a new menu, unrelated to the scale unit setup itself, but rather a toolbox of QoL tools.

**Comment by Omaaarz** [comment]
closed by PR #67
