### ISSUE TITLE
Do not install redundant workload instances

### ISSUE THREAD

**Issue by jususnja** [microsoft/SCMScaleUnitDevTools#47]
Workload instances to be installed are specified in UserConfig.xml, they can be either MES or WES. Alongside those workloads, we need to install SYS as well. The tool is appending SYS workload to installation automatically.
This means that we can end up with multiple redundant workload instanced installed.

For example if we want to install WES(Site1, wh1, USMF), we will automatically install SYS(USMF).
Then lets say we want to install MES(Site1, USMF) on the same environment, in this case we would update UserConfig.xml with the new MES workload instance, but the tool will generate SYS(USMF) automatically and we end up with the following workloads installed on the environment:

1.  WES(Site1, wh1, USMF)
2. SYS(USMF)
3. MES(Site1, USMF)
4. SYS(USMF)

Workload installation is idempotent so this will not harm the environment, the only problem is we have same workload instances stored as installed in the blob and status table.

It would be okay to install SYS(USMF) again if the workload definition was updated, in that case we Upgrade workload instance (same workload instance id, different versioned workload).
It would be okay to install new SYS workload instance for another company eg. SYS(DAT).
But the first example is not okay.

**Comment by AndreasHassing** [comment]
We're not installing redundant workloads, see [this](https://github.com/microsoft/SCMScaleUnitDevTools/blob/8f1a42f0a0ed8f28950a163cce0c0bb1447c0271/src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/WorkloadInstanceManager.cs#L225) code path, which generates a unique SYS workload per legal entity.
