### ISSUE TITLE
Add explanation of DB snapshots and how to reset Hub and Spoke

### ISSUE THREAD

**Issue by AndreasHassing** [microsoft/SCMScaleUnitDevTools#61]
Users are experiencing difficulties reverting back to a healthy state after installing workloads incorrectly via the dev tool.

We should have documentation to describe how to take Db snapshots and how to restore them - plus describing how to use the storage account clean-up tool within the dev tools.

**Comment by Antonstockmarr** [comment]
The new version of the documentation includes sections on how to restore the environment, including how to clean the storage accounts.
