### ISSUE TITLE
Validate if ScaleUnitId is valid

### ISSUE THREAD

**Issue by AndreasHassing** [microsoft/SCMScaleUnitDevTools#63]
Currently, anything can be placed in the `<ScaleUnitId>` field in `UserConfig.xml`. We should validate that the ID is within the mnemonic range (i.e. between @@ (0) and 1000).

**Comment by Antonstockmarr** [comment]
A way to do this could be to make the check in the `Validate()` method in [Config.cs](https://github.com/microsoft/SCMScaleUnitDevTools/blob/bdaae618a254dccfb19b20f59b2a13405d88d11a/src/ScaleUnitManagement/Utilities/Config.cs)
