### ISSUE TITLE
Validate InterAOS AAD app and tool AAD app are not the same

### ISSUE THREAD

**Issue by AndreasHassing** [microsoft/SCMScaleUnitDevTools#79]
In #76 the same AAD app was used for both the developer tool and inter-AOS communication, this should be enforced by the tool to avoid it from happening. The documentation dictates that two apps should be used for these different purposes.

The error went something like (from a request made from Spoke to Hub):
`An exception occured when authorizing - Entry point security access denied to current user for operation 'getInitializationData' on service 'ScaleUnitInitializationService'.`

**Comment by Antonstockmarr** [comment]
Can this be validated by comparing the appId of all scale units to the appId of the inter-AOS configuration?

**Comment by AndreasHassing** [comment]
> Can this be validated by comparing the appId of all scale units to the appId of the inter-AOS configuration?

@Antonstockmarr: Yes that sounds like a valid plan 😊.
