### ISSUE TITLE
Cannot clear storage account on LCS-hosted devbox

### ISSUE THREAD

**Issue by ABOZH** [microsoft/SCMScaleUnitDevTools#97]
I'm trying to re-enabling the scale unit, when I try to clear the azure storage, I get an error

Scale unit storage to clean up: 2
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
   at Azure.Storage.StorageConnectionString.Parse(String connectionString)
   at Azure.Storage.Blobs.BlobServiceClient..ctor(String connectionString, BlobClientOptions options)
   at ScaleUnitManagement.ScaleUnitFeatureManager.Common.StorageAccountCleaner.DeleteBlobContainers() in /home/runner/work/SCMScaleUnitDevTools/SCMScaleUnitDevTools/src/ScaleUnitManagement/ScaleUnitFeatureManager/Common/StorageAccountCleaner.cs:line 29

**Comment by AndreasHassing** [comment]
Hi @ABOZH, are you setting up two LCS-hosted dev boxes? Or using the `UseSingleOneBox` parameter to configure a single machine as Hub and Spoke both?

If the former; @Omaaarz / @Antonstockmarr: on LCS-hosted dev boxes a storage account is created per environment, so users need not add it as a parameter to `UserConfig.xml` - we should grab the value from `web.config` in that case.

**Comment by ABOZH** [comment]
Hi @AndreasHassing, i am using 2 separate LCS hosted devbox.

**Comment by ABOZH** [comment]
I can clean storage when decrypt web.config copy connection string value in userconfig.xml
Thank you for support

also (maybe this is important) in the step of removing the wordload from the hub, I was able to do this after changing the user from the default
![image](https://user-images.githubusercontent.com/89694939/134050495-9061f4cf-bd47-45bb-b066-d10ffc7992d7.png)
to this
![image](https://user-images.githubusercontent.com/89694939/134050593-90a929f9-b7e5-45a6-b6b2-05ba8963cdeb.png)

**Comment by AndreasHassing** [comment]
@Omaaarz do we have a tracking bug for user rights for workload deletion?
